[package]
name = "pipeline-core"
version = "0.1.0"
authors = ["Aaron Turon <aturon@mozilla.com>"]

[dependencies]
futures = "0.1"
zenoh-core = "0.1"
zenoh-service = { git = "https://github.com/zenoh-rs/zenoh-service" }
