---
relativeURLs: "true"
title: "Zenoh - The Zero Overhead, Pub/Sub, Store, Query, and Compute Protocol."
languageCode: "en-us"
canonifyURLs: "true"
pygmentsCodefences: true
pygmentsStyle: "manni"
googleAnalytics: UA-41082619-2
enableRobotsTXT: true
enableEmoji: true
singleViewStyle: "caspertwo"

sitemap:
    changefreq: "weekly"
    priority: 0.5

menu:
  docs:
    - identifier: "overview"
      name: "Overview"
      weight: 100
    - identifier: "getting_started"
      name: "Getting started"
      weight: 1000
    - identifier: "manual"
      name: "Reference manual"
      weight: 2000  
 